import type { Metadata } from "next";
import ConfigureAmplify from "@/utils/configureAmplify";
import OAuthListener from "@/components/auth/oauth-listener";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Massive App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={oswald.className}>
      <body className={oswald.className}>
        <ConfigureAmplify />
           <OAuthListener />
        {children}
      </body>
    </html>
  );
}
